doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Distributor:
                is_bundle: false
                mapping: true
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Distributor/Entity'
                prefix: 'App\Domain\Distributor\Entity'
                alias: Distributor
            Pharmacy:
                is_bundle: false
                mapping: true
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Pharmacy/Entity'
                prefix: 'App\Domain\Pharmacy\Entity'
                alias: Pharmacy
            Preparation:
                is_bundle: false
                mapping: true
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Preparation/Entity'
                prefix: 'App\Domain\Preparation\Entity'
                alias: Preparation
            PreparationUndefined:
                is_bundle: false
                mapping: true
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Preparation/Entity'
                prefix: 'App\Domain\Preparation\Entity'
                alias: PreparationUndefined
