version: '3'
services:
    nginx:
        build:
            context: ./docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8083:80"
    php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - mysql
    php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "3306:3306"
    node-watch:
        image: node:12.7-alpine
        volumes:
            - ./:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
    node:
        image: node:12.7-alpine
        volumes:
            - ./:/app
        working_dir: /app

volumes:
      mysql:
      composer:
