version: '3'
services:
  nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
    depends_on:
      - mysql
  php-cli:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33065:3306"

volumes:
  mysql:
  composer:
